- name: Update yum
  become: true
  become_user: root
  yum:
    name: "*"
    state: latest

- name: Install Git
  become: true
  become_user: root
  yum:
    name: git
    state: present
    lock_timeout: 180

- name: Install Rails Packages
  become: true
  become_user: root
  yum:
    name:
      - gcc-c++
      - glibc-headers
      - openssl-devel
      - libyaml-devel
      - readline-devel
      - zlib-devel
      - libffi-devel
      - ImageMagick
      - ImageMagick-devel
    state: present
