- name: Check If Nginx1 is Installed
  become: true
  shell: "amazon-linux-extras list"
  register: amazon_linux_extras_list
  changed_when: false

- name: Enable to Install Nginx1
  become_user: root
  become: true
  shell: "amazon-linux-extras enable nginx1"
  when: "'nginx1=latest' not in amazon_linux_extras_list.stdout"

- name: Install Nginx
  become_user: root
  become: true
  yum:
    name: nginx

- name: Set nginx.conf.j2 Template
  become_user: root
  become: true
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/nginx.conf"
    mode: "644"

- name: Change Owner /var/lib/nginx
  become_user: root
  become: true
  file:
    path: /var/lib/nginx/
    state: directory
    owner: ec2-user
    group: ec2-user
    recurse: true

- name: Restart Nginx
  become_user: root
  become: true
  systemd:
    name: nginx
    state: restarted

- name: Restart Puma
  become_user: root
  become: true
  systemd:
    name: puma
    state: restarted
