AWSTemplateFormatVersion: "2010-09-09"
Description: Application Stack for RaiseTech Lecture10

Parameters:
  KeyName: # キーペアはスタック作成時に選択する
  Description: The EC2 Key Pair to allow SSH access to the instance
  Type: "AWS::EC2::KeyPair::KeyName"

Resources:
  # EC2インスタンス: ap-northeast-1a
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: null # AMIが必要
      KeyName: !Ref KeyName
      InstanceType: t2.micro
      SubnetId: !ImportValue ExportedSubnet1Id
      SecurityGroupIds: !ImportValue ExportedEC2-SG-ID
      IamInstanceProfile: !ImportValue ExportedS3InstanceProfile
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          GroupSet:
            - !ImportValue ExportedEC2-SG-ID
          DeviceIndex: "0"
      Tags:
        - Key: Name
          Value: !Sub ${ExportedBaseName}-EC2

  # ALB
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: application
      Scheme: internet-facing
      IpAddressType: ipv4
      Subnets:
        - !ImportValue ExportedSubnet1Id
        - !ImportValue ExportedSubnet2Id
      SecurityGroups:
        - !ImportValue ExportedALB-SG-ID
      Tags:
        - Key: Name
          Value: !Sub ${ExportedBaseName}-ALB

  # リスナー
  ApplicationListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ApplicationTargetGroup
      Port: 80
      Protocol: HTTP

  # ターゲットグループ
  ApplicationTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${ExportedBaseName}-Target-Group
      Port: 80
      Protocol: HTTP
      TargetType: instance
      VpcId: !ImportValue ExportedVpcId
      IpAddressType: ipv4
      Matcher:
        HttpCode: 200
      HealthCheck:
        Path: /
        Port: 80
        Protocol: HTTP
        TimeoutSeconds: 5
        HealthyThresholdCount: 2
        UnhealthyThresholdCount: 2
      Tags:
        - Key: Name
          Value: !Sub ${ExportedBaseName}-Target-Group

  # S3
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ExportedBaseName}-bucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Name
          Value: !Sub ${ExportedBaseName}-S3
